Repository GSG-CF04/TOP-CHEF, pull requests merged in 2021-12, with the labels that each got.

#50 fetch Food categories from api (categoriesFood page)
  js/categoryFood.js
  otherPages/categories/categories.css
  otherPages/categories/categoriesFood.html
Labels: Done

#56 Write JS for Search in Page Type Food
  .vscode/settings.json
  js/typeFood.js
  otherPages/type/type.css
  otherPages/type/typeFood.html
Labels: awaiting-review

#57 Fetch drink categories api
  js/categoryDrink.js
  js/categoryFood.js
  otherPages/categories/categories.css
  otherPages/categories/categoriesDrink.html
Labels: Done

#60 [Js] fetch type drink as category selected
  js/typeDrink.js
  js/typeFood.js
  otherPages/type/typeDrink.html
  otherPages/type/typeFood.html
Labels: Done

#61 [HTML- CSS-Responsive] Popup
  otherPages/type/type.css
  otherPages/type/typeDrink.html
  otherPages/type/typeFood.html
Labels: approved

#64 Slider in categoriesFood page & categoriesDrink page
  otherPages/categories/categories.css
  otherPages/categories/categoriesDrink.html
  otherPages/categories/categoriesFood.html
Labels: approved

#62 [Js] Pop-up (typeFood page)
  js/typeFood.js
  otherPages/type/type.css
  otherPages/type/typeFood.html
Labels: approved

#65 Js Slider (categoriesFood Page and categoriesDrink Page )
  js/categoryDrink.js
  js/categoryFood.js
  otherPages/categories/carouselLibrary/carousel.css
  otherPages/categories/carouselLibrary/carousel.js
  otherPages/categories/categories.css
  otherPages/categories/categoriesDrink.html
  otherPages/categories/categoriesFood.html
  style.css
Labels: approved

#63 [Js] Pop-up (typeDrink page)
  js/typeDrink.js
  otherPages/type/typeDrink.html
Labels: awaiting-review

#67 Clean Code And Update ReadMe
  README.md
  js/typeDrink.js
  js/typeFood.js
  otherPages/type/type.css
  otherPages/type/typeDrink.html
  otherPages/type/typeFood.html
Labels: approved

#69 Final touches fot all pages
  README.md
  otherPages/categories/categories.css
  otherPages/categories/categoriesDrink.html
  otherPages/categories/categoriesFood.html
  otherPages/header.css
  otherPages/home/home.css
  otherPages/home/home.html
  otherPages/type/type.css
  otherPages/type/typeDrink.html
  otherPages/type/typeFood.html
  style.css
Labels: awaiting-review
